#!/usr/bin/python

import sys
import csv
import json

json_file = sys.argv[1]
if len(sys.argv) > 2:
    csv_file = sys.argv[2]
else:
    csv_file = "results.csv"

with open(json_file) as file:
     data = json.load(file)

with open(csv_file, "w") as file:
     csv_file = csv.writer(file)
     for item in data:
         csv_file.writerow([item['test case'], item['size'],
                           item['iterations'], item['minimum run time (s)'],
                           item['average run time (s)'], item['maximum run time (s)'],
                           item['median run time (s)'], item['standard deviation of run time (s)'],
                           item['avg frames per second (fps)']])
